[package]
authors = ["Jacob Lindahl <aviator9402@gmail.com>"]
description = "Easily generate furigana for various document formats"
edition = "2021"
name = "autoruby"
version = "0.1.0"

[features]
default = ["dict-autodownload"]
dict-autodownload = []

[dependencies]
lindera = {version = "0.19.0", features = ["ipadic"]}
nom = "7.1.1"
reqwest = "0.11.13"
rusqlite = {version = "0.28.0", features = ["bundled"]}
serde = "1.0.151"
wana_kana = "2.1.0"

[build-dependencies]
nom = "7.1.1"
reqwest = "0.11.13"
rusqlite = {version = "0.28.0", features = ["bundled"]}
tokio = {version = "1.23.0", features = ["full"]}
