[package]
authors = ["Jacob Lindahl <aviator9402@gmail.com>"]
categories = ["text-processing", "localization", "accessibility"]
description = "Easily generate furigana for various document formats"
edition = "2021"
license = "GPL-3.0-only"
name = "autoruby"
repository = "https://github.com/encody/autoruby"
version = "0.1.0"

[features]
default = ["frequency-full", "dict-autodownload"]
dict-autodownload = []
frequency-full = ["jmdict/full"]

[dependencies]
bincode = "1.3.3"
jmdict = "2.0.0"
lindera = {version = "0.19.5", features = ["ipadic"]}
nom = "7.1.1"
once_cell = "1.17.0"
reqwest = "0.11.13"
serde = "1.0.151"
thiserror = "1.0.38"
wana_kana = "3.0.0"

[build-dependencies]
bincode = "1.3.3"
dotenvy = "0.15.6"
jmdict = "2.0.0"
nom = "7.1.3"
reqwest = "0.11.14"
serde = "1.0.151"
tokio = {version = "1.25.0", features = ["full"]}
