[package]
edition = "2021"
name = "autoruby-cli"
version = "0.1.0"

[dependencies]
autoruby = {path = "../autoruby", features = ["frequency-full"], default-features = false}
clap = {version = "4.0.30", features = ["derive"]}
directories = "4.0.1"
envy = "0.4.2"
rusqlite = "0.28.0"
serde = "1.0.152"
tokio = "1.23.1"

[[bin]]
name = "autoruby"
path = "src/main.rs"
